const ACTION_TYPES = {
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  GET_HEROES_REQUEST: 'GET_TASKS_REQUEST',
  GET_HEROES_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_HEROES_ERROR: 'GET_TASKS_ERROR'
};

export default ACTION_TYPES;
