const ACTION_TYPES = {

  CREATE_TASK: 'CREATE_TASK',
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  GET_TASKS: 'GET_TASKS',
  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',

  UPDATE_TASK: 'UPDATE_TASK',

  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASK_REQUEST: 'REMOVE_TASK_REQUEST',
  REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
  REMOVE_TASK_ERROR: 'REMOVE_TASK_ERROR',
};

export default ACTION_TYPES;
