const ACTION_TYPES = {

  CREATE_TASK_ACTION: 'CREATE_TASK_ACTION',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  GET_TASKS_ACTION: 'GET_TASKS_ACTION',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',

  REMOVE_TASK_ACTION: 'REMOVE_TASK_ACTION',
  REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
  REMOVE_TASK_ERROR: 'REMOVE_TASK_ERROR',
};

export default ACTION_TYPES;
